# Generated by Django 5.1 on 2024-10-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webVinilos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilo',
            name='codigo',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vinilo',
            name='contacto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vinilo',
            name='formato',
            field=models.CharField(choices=[('Vinilo', 'Vinilo'), ('Cassette', 'Cassette'), ('CD', 'CD')], default='Vinilo', max_length=50),
        ),
        migrations.AddField(
            model_name='vinilo',
            name='inserto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
